name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag inventory-app:latest

    - name: Run tests in Docker container
      run: docker run --rm inventory-app:latest python3 -m unittest discover -s tests
