name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run commands
      run: |
        echo "This is a command running in CMD"
        uname -a
        ifconfig
